export const BUSINESS_MARKETING_TABS = [
  { id: 'all', label: 'All Campaigns' },
  { id: 'active', label: 'Active' },
  { id: 'scheduled', label: 'Scheduled' },
  { id: 'completed', label: 'Completed' },
  { id: 'drafts', label: 'Drafts' },
  { id: 'collaborations', label: 'Collaborations' },
  { id: 'analytics', label: 'Analytics' },
]

export const BUSINESS_MARKETING_FILTERS = {
  types: [
    { label: 'All Types', value: 'all' },
    { label: 'Brand Awareness', value: 'Brand Awareness' },
    { label: 'Product Promotion', value: 'Product Promotion' },
    { label: 'Education Promo', value: 'Education Promo' },
    { label: 'Channel Sponsorship', value: 'Channel Sponsorship' },
  ],
  platforms: [
    { label: 'All Platforms', value: 'all' },
    { label: 'Instagram', value: 'Instagram' },
    { label: 'TikTok', value: 'TikTok' },
    { label: 'YouTube', value: 'YouTube' },
    { label: 'X', value: 'X' },
  ],
  statuses: [
    { label: 'All Status', value: 'all' },
    { label: 'Active', value: 'Active' },
    { label: 'Scheduled', value: 'Scheduled' },
    { label: 'Completed', value: 'Completed' },
    { label: 'Draft', value: 'Draft' },
  ],
}

export const BUSINESS_MARKETING_METRICS = [
  { icon: 'campaign', label: 'Active Campaigns', trend: '3 new this week', tone: 'purple', value: '12' },
  { icon: 'send', label: 'Creator Collaborations', trend: '12 new this week', tone: 'orange', value: '48' },
  { icon: 'eye', label: 'Total Reach', trend: '+18% from last week', tone: 'green', value: '256K' },
  { icon: 'thumbs', label: 'Engagements', trend: '+22% from last week', tone: 'blue', value: '18.6K' },
  { icon: 'spend', label: 'Total Spent', trend: 'On all campaigns', tone: 'purple', value: 'KES 245,000' },
]

export const BUSINESS_MARKETING_CAMPAIGNS = [
  {
    id: 'level-up-skills',
    title: 'Level Up Your Skills',
    type: 'Brand Awareness',
    description: 'Promoting Zetech Studios digital services to help students level up their skills.',
    status: 'Active',
    platforms: ['Instagram', 'TikTok'],
    reach: '82.4K',
    engagement: '6.2K',
    budget: 'KES 25,000',
    creators: ['AM', 'BO', 'CN'],
    creatorOverflow: 7,
    timelineLabel: 'Ends in',
    timelineValue: '5 days',
    thumbnailTitle: 'LEVEL UP YOUR SKILLS',
    thumbnailMeta: '#ZetechPower',
    tone: 'navy',
  },
  {
    id: 'summer-collection-launch',
    title: 'Summer Collection Launch',
    type: 'Product Promotion',
    description: 'New summer collection launch for our brand with student creators.',
    status: 'Active',
    platforms: ['Instagram'],
    reach: '64.1K',
    engagement: '4.8K',
    budget: 'KES 30,000',
    creators: ['NW', 'KO', 'LA'],
    creatorOverflow: 5,
    timelineLabel: 'Ends in',
    timelineValue: '2 days',
    thumbnailTitle: 'SUMMER COLLECTION IS HERE!',
    thumbnailMeta: 'Launch',
    tone: 'coral',
  },
  {
    id: 'stay-hydrated',
    title: 'Stay Hydrated Campaign',
    type: 'Brand Awareness',
    description: 'Promoting healthy habits and our hydration bottle among students.',
    status: 'Scheduled',
    platforms: ['TikTok', 'YouTube'],
    reach: '45.2K',
    engagement: '3.1K',
    budget: 'KES 20,000',
    creators: ['JM', 'TS', 'RE'],
    creatorOverflow: 4,
    timelineLabel: 'Starts on',
    timelineValue: 'May 20, 2025',
    thumbnailTitle: 'STAY HYDRATED',
    thumbnailMeta: 'Stay focused',
    tone: 'green',
  },
  {
    id: 'exam-prep-made-easy',
    title: 'Exam Prep Made Easy',
    type: 'Education Promo',
    description: 'Promoting study resources and online courses for exam preparation.',
    status: 'Completed',
    platforms: ['YouTube', 'Instagram'],
    reach: '64.3K',
    engagement: '4.5K',
    budget: 'KES 18,000',
    creators: ['PO', 'BA', 'MW'],
    creatorOverflow: 6,
    timelineLabel: 'Completed on',
    timelineValue: 'May 10, 2025',
    thumbnailTitle: 'EXAM PREP MADE EASY',
    thumbnailMeta: 'Study pack',
    tone: 'lavender',
  },
  {
    id: 'creator-podcast-sponsor',
    title: 'Creator Podcast Sponsor',
    type: 'Channel Sponsorship',
    description: 'Sponsoring student podcast episodes around campus entrepreneurship.',
    status: 'Draft',
    platforms: ['YouTube', 'X'],
    reach: '18.7K',
    engagement: '1.2K',
    budget: 'KES 12,000',
    creators: ['DN', 'AW'],
    creatorOverflow: 2,
    timelineLabel: 'Drafted',
    timelineValue: 'Yesterday',
    thumbnailTitle: 'PODCAST SPONSOR',
    thumbnailMeta: 'Campus talk',
    tone: 'orange',
  },
  {
    id: 'micro-creator-reviews',
    title: 'Micro Creator Reviews',
    type: 'Product Promotion',
    description: 'Student creators testing product samples and posting authentic reviews.',
    status: 'Active',
    platforms: ['TikTok', 'Instagram'],
    reach: '39.8K',
    engagement: '3.9K',
    budget: 'KES 22,000',
    creators: ['SK', 'GA', 'LK'],
    creatorOverflow: 8,
    timelineLabel: 'Ends in',
    timelineValue: '8 days',
    thumbnailTitle: 'REAL STUDENT REVIEWS',
    thumbnailMeta: 'Product seed',
    tone: 'blue',
  },
]

export const BUSINESS_MARKETING_CREATE_OPTIONS = [
  {
    id: 'social',
    title: 'Social Media Campaign',
    description: 'Get your brand promoted on student social media.',
    icon: 'campaign',
    tone: 'purple',
  },
  {
    id: 'sponsor',
    title: 'Sponsor a Channel',
    description: 'Sponsor student YouTube channels, blogs or podcasts.',
    icon: 'video',
    tone: 'orange',
  },
  {
    id: 'seeding',
    title: 'Product Seeding',
    description: 'Send products to student creators for reviews and mentions.',
    icon: 'gift',
    tone: 'green',
  },
]

export const BUSINESS_MARKETING_PLATFORMS = [
  { label: 'Instagram', value: 78, tone: 'pink' },
  { label: 'TikTok', value: 72, tone: 'dark' },
  { label: 'YouTube', value: 48, tone: 'red' },
  { label: 'X (Twitter)', value: 32, tone: 'dark' },
  { label: 'Facebook', value: 18, tone: 'blue' },
]
