export const BUSINESS_OPPORTUNITY_TABS = [
  { id: 'opportunities', label: 'Opportunities' },
  { id: 'completed', label: 'Completed' },
  { id: 'drafts', label: 'Drafts' },
  { id: 'archived', label: 'Archived' },
]

export const BUSINESS_OPPORTUNITY_FILTERS = {
  budgets: [
    { label: 'All Budget', value: 'all' },
    { label: 'Under KES 20K', value: 'under-20' },
    { label: 'KES 20K+', value: 'over-20' },
  ],
  categories: [
    { label: 'All Categories', value: 'all' },
    { label: 'Social Media', value: 'Social Media' },
    { label: 'UI/UX Design', value: 'UI/UX Design' },
    { label: 'Web Development', value: 'Web Development' },
    { label: 'Data Analysis', value: 'Data Analysis' },
    { label: 'Video Editing', value: 'Video Editing' },
  ],
  skills: [
    { label: 'All Skills', value: 'all' },
    { label: 'Canva', value: 'Canva' },
    { label: 'Figma', value: 'Figma' },
    { label: 'JavaScript', value: 'JavaScript' },
    { label: 'SQL', value: 'SQL' },
    { label: 'Premiere Pro', value: 'Premiere Pro' },
  ],
  stages: [
    { label: 'All Stages', value: 'all' },
    { label: 'Open', value: 'Open' },
    { label: 'In Review', value: 'In Review' },
    { label: 'Shortlisted', value: 'Shortlisted' },
    { label: 'Completed', value: 'Completed' },
    { label: 'Draft', value: 'Draft' },
    { label: 'Archived', value: 'Archived' },
  ],
}

export const BUSINESS_OPPORTUNITY_BIDDER_CANDIDATES = [
  {
    id: 'aisha-mwangi',
    availability: 'Weekdays, 12 hrs/week',
    match: 94,
    name: 'Aisha Mwangi',
    school: 'Strathmore University',
    skills: ['Social Media', 'Content Creation', 'Canva'],
    status: 'Available this week',
    tone: 'purple',
  },
  {
    id: 'grace-wanjiku',
    availability: 'Flexible, remote',
    match: 89,
    name: 'Grace Wanjiku',
    school: 'Kenyatta University',
    skills: ['Copywriting', 'Analytics', 'Social Media'],
    status: 'Responds within 2h',
    tone: 'blue',
  },
  {
    id: 'kevin-mutua',
    availability: 'Evenings and weekends',
    match: 83,
    name: 'Kevin Mutua',
    school: 'Multimedia University',
    skills: ['UI/UX Design', 'Figma', 'Prototyping'],
    status: 'Portfolio verified',
    tone: 'green',
  },
  {
    id: 'brian-otieno',
    availability: 'Part-time, hybrid',
    match: 78,
    name: 'Brian Otieno',
    school: 'Jomo Kenyatta University',
    skills: ['Data Analysis', 'SQL', 'Visualization'],
    status: 'Open to interviews',
    tone: 'orange',
  },
]

export const BUSINESS_OPPORTUNITY_ROWS = [
  {
    id: 'social-media-management',
    applicants: 12,
    budget: 'KES 15,000',
    category: 'Social Media',
    company: 'Zetech Studios',
    description: 'We are looking for a creative student to manage our social media channels and grow our online presence.',
    icon: 'campaign',
    skills: ['Social Media', 'Content Creation', 'Canva'],
    skillOverflow: 2,
    status: 'Open',
    time: '2 hours ago',
    title: 'Social Media Management',
    tone: 'coral',
  },
  {
    id: 'mobile-ui-ux-design',
    applicants: 8,
    budget: 'KES 25,000',
    category: 'UI/UX Design',
    company: 'TechNova Solutions',
    description: 'Design a clean and modern UI/UX for our new mobile application.',
    icon: 'design',
    skills: ['UI/UX Design', 'Figma', 'Prototyping'],
    skillOverflow: 1,
    status: 'Open',
    time: '5 hours ago',
    title: 'UI/UX Design for Mobile App',
    tone: 'green',
  },
  {
    id: 'website-development',
    applicants: 15,
    budget: 'KES 30,000',
    category: 'Web Development',
    company: 'BrightWave Digital',
    description: 'Develop a responsive website for our company using modern technologies.',
    icon: 'code',
    skills: ['Web Development', 'HTML', 'CSS', 'JavaScript'],
    skillOverflow: 2,
    status: 'In Review',
    time: '1 day ago',
    title: 'Website Development',
    tone: 'blue',
  },
  {
    id: 'data-analysis-project',
    applicants: 9,
    budget: 'KES 18,000',
    category: 'Data Analysis',
    company: 'DataEdge Analytics',
    description: 'Analyze sales data and generate insights to help improve business performance.',
    icon: 'analytics',
    skills: ['Data Analysis', 'Excel', 'SQL', 'Visualization'],
    skillOverflow: 1,
    status: 'Shortlisted',
    time: '2 days ago',
    title: 'Data Analysis Project',
    tone: 'orange',
  },
  {
    id: 'campaign-video-editing',
    applicants: 6,
    budget: 'KES 10,000',
    category: 'Video Editing',
    company: 'Creative Hive',
    description: 'Edit short-form videos for our marketing campaign across social platforms.',
    icon: 'video',
    skills: ['Video Editing', 'Premiere Pro', 'After Effects'],
    skillOverflow: 1,
    status: 'Draft',
    time: '3 days ago',
    title: 'Video Editing for Campaign',
    tone: 'purple',
  },
  {
    id: 'completed-campus-activation',
    applicants: 18,
    budget: 'KES 22,000',
    category: 'Social Media',
    company: 'Zetech Studios',
    description: 'Campus activation support completed with final engagement reporting and student feedback.',
    icon: 'campaign',
    skills: ['Events', 'Social Media', 'Reporting'],
    skillOverflow: 0,
    status: 'Completed',
    time: '1 week ago',
    title: 'Campus Activation Support',
    tone: 'green',
  },
  {
    id: 'archived-product-research',
    applicants: 11,
    budget: 'KES 16,000',
    category: 'Data Analysis',
    company: 'Zetech Studios',
    description: 'Product research brief archived after business scope changed.',
    icon: 'analytics',
    skills: ['Research', 'Surveys', 'Reporting'],
    skillOverflow: 0,
    status: 'Archived',
    time: '2 weeks ago',
    title: 'Student Product Research',
    tone: 'neutral',
  },
]

export const BUSINESS_OPPORTUNITY_SKILL_DEMAND = [
  { label: 'Social Media', value: 42, tone: 'purple' },
  { label: 'UI/UX Design', value: 34, tone: 'orange' },
  { label: 'Web Development', value: 28, tone: 'green' },
  { label: 'Data Analysis', value: 18, tone: 'blue' },
  { label: 'Video Editing', value: 16, tone: 'pink' },
]

export const BUSINESS_OPPORTUNITY_ACTIVITY = [
  { actor: 'Aisha Mwangi', initials: 'AM', detail: 'applied for Social Media Management', time: '10m ago', tone: 'coral' },
  { actor: 'Brian Otieno', initials: 'BO', detail: 'was shortlisted for UI/UX Design for Mobile App', time: '1h ago', tone: 'orange' },
  { actor: 'Grace Wanjiku', initials: 'GW', detail: 'submitted for Website Development', time: '3h ago', tone: 'blue' },
  { actor: 'Kevin Mutua', initials: 'KM', detail: 'was moved to Interview stage', time: '5h ago', tone: 'green' },
]

export const BUSINESS_OPPORTUNITY_SUMMARY = [
  { icon: 'briefcase', label: 'Total', tone: 'purple', value: 24 },
  { icon: 'check', label: 'Open', tone: 'green', value: 8 },
  { icon: 'review', label: 'In Review', tone: 'blue', value: 6 },
  { icon: 'users', label: 'Shortlisted', tone: 'purple', value: 5 },
  { icon: 'check', label: 'Completed', tone: 'green', value: 1 },
  { icon: 'draft', label: 'Drafts', tone: 'neutral', value: 3 },
  { icon: 'closed', label: 'Archived', tone: 'orange', value: 1 },
]
