export const BUSINESS_OPPORTUNITY_BRIEF_STEPS = [
  { id: 'details', label: 'Opportunity Details', meta: 'Basic information' },
  { id: 'requirements', label: 'Requirements', meta: 'Skills & qualifications' },
  { id: 'scope', label: 'Scope & Budget', meta: 'Deliverables & budget' },
  { id: 'review', label: 'Review & Publish', meta: 'Review and publish' },
]

export const BUSINESS_OPPORTUNITY_BRIEF_DEFAULTS = {
  acceptanceCriteria: 'Content is approved before publishing, captions follow the brand voice, analytics are submitted weekly, and all final assets are handed over in editable formats.',
  applicationDeadline: '',
  availability: 'Flexible',
  budget: '15,000',
  bidderInstructions: 'Apply with 2 relevant content samples, your weekly availability, expected turnaround time, and any questions about the campaign scope.',
  category: 'Social Media',
  companyDescription: 'We are a digital creative studio helping brands build strong online presence through content and design.',
  companyName: 'Zetech Studios',
  deliverables: 'Weekly content calendar, 8 social posts, basic analytics report, and final campaign summary.',
  duration: '4 weeks',
  engagementMode: 'Remote',
  experienceLevel: 'Any level',
  mustHave: ['Social Media', 'Content Creation', 'Canva'],
  opportunityType: 'Project',
  opportunitySplash: null,
  paymentTerms: 'Milestone-based',
  portfolioRequired: 'Portfolio samples required',
  preferredQualifications: 'Experience managing Instagram or TikTok pages for clubs, student groups, or small businesses.',
  qualificationQuestions: [
    'Describe one relevant project you have completed and the result you achieved.',
    'What is your weekly availability for this opportunity?',
  ],
  requiredAttachments: [
    { id: 'required-portfolio-samples', label: 'Portfolio samples', fileType: 'PDF' },
    { id: 'required-content-examples', label: 'Two relevant content examples', fileType: 'Link' },
  ],
  screeningFocus: 'Portfolio samples, writing quality, brand voice, and weekly availability.',
  skills: 'Social Media, Content Creation, Canva',
  summary: "We're looking for a creative student to manage our social media channels and grow our online presence.",
  title: 'Social Media Management',
  visibility: 'Visible to all students',
  scopeMode: 'deliverable',
  milestoneScopes: [
    {
      id: 'milestone-planning',
      title: 'Campaign kickoff and content plan',
      type: 'Document Deliverables',
      description: 'Create the campaign direction, content calendar, and approval plan before production starts.',
      submissionMethod: 'Google Docs share link or PDF upload with clear stage notes.',
      verificationMethod: 'Company review against the brief, comments, and approval checklist.',
      evidenceRequired: 'Content calendar, planned captions, platform schedule, and approval notes.',
      acceptanceCriteria: 'Plan covers all required platforms, dates, tone, and approval responsibilities.',
      sampleWork: [
        { id: 'milestone-planning-sample-calendar', label: 'Example content calendar', fileType: 'PDF', files: [] },
      ],
      paymentRelease: 'Release after kickoff materials are approved.',
      budget: '3,000',
      paymentPercent: '20',
      isSequential: true,
    },
    {
      id: 'milestone-production',
      title: 'Content production and delivery',
      type: 'Hybrid Deliverables',
      description: 'Produce and hand over the approved campaign content package.',
      submissionMethod: 'Component-specific submissions using files, links, documents, or screenshots as needed.',
      verificationMethod: 'Each component is verified using its documented method before stage approval.',
      evidenceRequired: 'Final content assets, source links/files, and production notes.',
      acceptanceCriteria: 'All approved content is complete, usable, and aligned to the agreed campaign plan.',
      sampleWork: [
        { id: 'milestone-production-sample-assets', label: 'Approved asset direction sample', fileType: 'Image', files: [] },
      ],
      paymentRelease: 'Release after production milestone approval.',
      budget: '7,500',
      paymentPercent: '50',
      isSequential: true,
    },
    {
      id: 'milestone-reporting',
      title: 'Publishing proof and performance report',
      type: 'Stats & Metrics Deliverables',
      description: 'Submit final evidence that the campaign was published and measured.',
      submissionMethod: 'Analytics screenshots, posting proof, or API-verifiable metrics where available.',
      verificationMethod: 'Baseline comparison, evidence review, and metric validation.',
      evidenceRequired: 'Posting proof, analytics screenshots, baseline, measurement window, and final report.',
      acceptanceCriteria: 'Evidence matches the approved campaign scope and measurement window.',
      sampleWork: [
        { id: 'milestone-reporting-sample-report', label: 'Reporting sample format', fileType: 'Spreadsheet', files: [] },
      ],
      paymentRelease: 'Release after reporting milestone approval.',
      budget: '4,500',
      paymentPercent: '30',
      isSequential: true,
    },
  ],
  deliverableMilestones: [
    {
      id: 'deliverable-file-assets',
      title: 'Create branded social media assets',
      type: 'File Asset Deliverables',
      workflow: 'File Asset Deliverables',
      description: 'Design and upload the final campaign graphics plus editable source files.',
      submissionMethod: 'Direct upload to Zumbarl with final PNG/PDF exports and source files where required.',
      verificationMethod: 'Company review, originality check, and tracked revision cycle.',
      evidenceRequired: 'PNG, JPG, PDF, SVG, MP4, MOV, AI, PSD, Figma link, or Canva link.',
      acceptanceCriteria: 'No watermarks, follows brand assets, and includes editable source files for work above KES 5,000.',
      sampleWork: [
        { id: 'deliverable-file-assets-sample-brand', label: 'Brand asset reference', fileType: 'Image', files: [] },
      ],
      paymentRelease: 'Release after company approval and file verification.',
      budget: '6,000',
      paymentPercent: '40',
      isSequential: true,
    },
    {
      id: 'deliverable-proof-posting',
      title: 'Submit posting proof',
      type: 'Proof-Based Deliverables',
      workflow: 'Proof-Based Deliverables',
      description: 'Provide evidence that approved content was posted or delivered as agreed.',
      submissionMethod: 'Timestamped screenshot, GPS/photo proof where relevant, or WhatsApp confirmation.',
      verificationMethod: 'Evidence review, timestamp validation, and recipient/platform confirmation.',
      evidenceRequired: 'Screenshots, geo-tagged photos, GPS check-in, or WhatsApp confirmation.',
      acceptanceCriteria: 'Evidence matches the agreed platform, location, recipient, and timeline.',
      sampleWork: [
        { id: 'deliverable-proof-posting-sample-proof', label: 'Accepted proof example', fileType: 'Image', files: [] },
      ],
      paymentRelease: 'Release after proof is verified.',
      budget: '4,500',
      paymentPercent: '30',
      isSequential: true,
    },
    {
      id: 'deliverable-metrics',
      title: 'Submit performance analytics',
      type: 'Stats & Metrics Deliverables',
      workflow: 'Stats & Metrics Deliverables',
      description: 'Share the before-and-after metrics for reach, engagement, and campaign performance.',
      submissionMethod: 'Platform analytics screenshots or API-verifiable metrics where available.',
      verificationMethod: 'Baseline comparison, analytics screenshot review, and API verification where supported.',
      evidenceRequired: 'Instagram Insights, TikTok Analytics, WhatsApp Channel Analytics, or accepted metric screenshots.',
      acceptanceCriteria: 'Includes baseline, measurement window, target metric, and accepted evidence format.',
      sampleWork: [
        { id: 'deliverable-metrics-sample-analytics', label: 'Analytics report sample', fileType: 'PDF', files: [] },
      ],
      paymentRelease: 'Release after metric achievement is verified.',
      budget: '4,500',
      paymentPercent: '30',
      isSequential: true,
    },
  ],
}

export const BUSINESS_OPPORTUNITY_BRIEF_TYPE_OPTIONS = [
  {
    id: 'Project',
    label: 'Project',
    meta: 'One-time project with defined deliverables',
  },
  {
    id: 'Task',
    label: 'Task',
    meta: 'Small task or quick job',
  },
]

export const BUSINESS_OPPORTUNITY_BRIEF_SELECTS = {
  availability: ['Flexible', 'Immediate', 'Weekdays', 'Weekends'],
  category: ['Social Media', 'UI/UX Design', 'Web Development', 'Data Analysis', 'Video Editing', 'Marketing & Communications'],
  deliverableType: [
    'File Asset Deliverables',
    'Code & Development Deliverables',
    'Document Deliverables',
    'Stats & Metrics Deliverables',
    'Proof-Based Deliverables',
    'Hybrid Deliverables',
  ],
  duration: ['< 1 days', '1-2 days', '1-2 weeks', '3-4 weeks', '2-5 months', '6+ months ', 'Flexible / To be agreed'],
  engagementMode: ['Remote', 'Hybrid', 'On-site'],
  experienceLevel: ['Any level', 'Beginner', 'Intermediate', 'Advanced'],
  paymentTerms: ['Milestone-based', 'Fixed price', 'Hourly', 'Pay on completion'],
  portfolioRequired: ['Portfolio samples required', 'Portfolio optional', 'No portfolio needed'],
}

export const BUSINESS_OPPORTUNITY_BRIEF_SKILLS = [
  'Social Media',
  'Content Creation',
  'Canva',
  'Copywriting',
  'Analytics',
  'Video Editing',
]

export const BUSINESS_OPPORTUNITY_BRIEF_SETTINGS = [
  { label: 'Visibility', value: 'Visible to all students', icon: 'eye' },
  { label: 'All students', value: 'Any student can apply', icon: 'users' },
  { label: 'Auto close', value: '30 days after deadline', icon: 'calendar' },
]
