import type { FastifyInstance } from 'fastify'
import { requireRoles, roleGroups } from '../../../../lib/security.js'
import { cancelCallController, commentOnPostController, commentOnStoryController, connectProfileController, contributeToChamaController, createCallController, createGroupController, createManagedProfilePostController, createMessageController, createPostController, createProjectGroupMessageController, createStoryController, decideAnnouncementRequestController, endCallController, followProfileController, heartbeatController, joinGroupController, listAnnouncementRequestsController, listConnectFeedController, listConversationsController, listGroupsController, listIncomingCallsController, listMessagesController, listMyManagedProfilesController, listProjectGroupMessagesController, listStoriesController, reactToPostController, reactToStoryCommentController, reactToStoryController, readAnnouncementTargetsController, readCallController, readConnectProfileController, readManagedProfileController, readRelationshipController, readStoryEngagementController, readTagContextController, realtimeEventsController, reportPostController, respondToCallController, searchEventOrganizersController, submitPostForAnnouncementController, updateManagedProfileController, updateOwnedPostController, upsertConnectProfileController } from '../../controllers/connect/index.js'
import { extractSocialMetricsController, readSocialMarketingProfileController, saveSocialMetricsController } from '../../controllers/connect/index.js'
import { addManagedProfileManagerController, createManagedProfileController, removeManagedProfileManagerController } from '../../controllers/connect/index.js'
import { followManagedProfileController } from '../../controllers/connect/index.js'
async function registerConnectRoutes(app: FastifyInstance) {
  const students = requireRoles(...roleGroups.student, ...roleGroups.admin, ...roleGroups.moderator)
  const authenticatedUsers = requireRoles(...roleGroups.student, ...roleGroups.business, ...roleGroups.admin, ...roleGroups.moderator)
  const announcementAdmins = requireRoles(...roleGroups.admin, ...roleGroups.moderator, 'CAMPUS_MANAGER')
  app.post('/presence/heartbeat', { preHandler: authenticatedUsers }, heartbeatController)
  app.post('/calls', { preHandler: authenticatedUsers }, createCallController)
  app.get('/calls/incoming', { preHandler: authenticatedUsers }, listIncomingCallsController)
  app.get('/calls/:id', { preHandler: authenticatedUsers }, readCallController)
  app.patch('/calls/:id/respond', { preHandler: authenticatedUsers }, respondToCallController)
  app.patch('/calls/:id/cancel', { preHandler: authenticatedUsers }, cancelCallController)
  app.patch('/calls/:id/end', { preHandler: authenticatedUsers }, endCallController)
  app.get('/events', { preHandler: authenticatedUsers }, realtimeEventsController)
  app.get('/messages/conversations', { preHandler: authenticatedUsers }, listConversationsController)
  app.get('/messages', { preHandler: authenticatedUsers }, listMessagesController)
  app.post('/messages', { preHandler: authenticatedUsers }, createMessageController)
  app.get('/messages/project-group/:projectId', { preHandler: authenticatedUsers }, listProjectGroupMessagesController)
  app.post('/messages/project-group/:projectId', { preHandler: authenticatedUsers }, createProjectGroupMessageController)
  app.get('/feed', { preHandler: students }, listConnectFeedController)
  app.get('/managed-profiles/me', { preHandler: authenticatedUsers }, listMyManagedProfilesController)
  app.post('/managed-profiles', { preHandler: authenticatedUsers }, createManagedProfileController)
  app.get('/managed-profiles/:id', { preHandler: authenticatedUsers }, readManagedProfileController)
  app.patch('/managed-profiles/:id', { preHandler: authenticatedUsers }, updateManagedProfileController)
  app.post('/managed-profiles/:id/follow', { preHandler: authenticatedUsers }, followManagedProfileController)
  app.delete('/managed-profiles/:id/follow', { preHandler: authenticatedUsers }, followManagedProfileController)
  app.post('/managed-profiles/:id/posts', { preHandler: authenticatedUsers }, createManagedProfilePostController)
  app.post('/managed-profiles/:id/managers', { preHandler: authenticatedUsers }, addManagedProfileManagerController)
  app.delete('/managed-profiles/:id/managers/:userId', { preHandler: authenticatedUsers }, removeManagedProfileManagerController)
  app.get('/profile', { preHandler: students }, readConnectProfileController)
  app.post('/profile', { preHandler: students }, upsertConnectProfileController)
  app.get('/profile/marketing', { preHandler: students }, readSocialMarketingProfileController)
  app.post('/profile/marketing/extract', { preHandler: students }, extractSocialMetricsController)
  app.post('/profile/marketing/accounts', { preHandler: students }, saveSocialMetricsController)
  app.get('/profiles/:id/relationship', { preHandler: students }, readRelationshipController)
  app.post('/profiles/:id/follow', { preHandler: students }, followProfileController)
  app.delete('/profiles/:id/follow', { preHandler: students }, followProfileController)
  app.post('/profiles/:id/connect', { preHandler: students }, connectProfileController)
  app.delete('/profiles/:id/connect', { preHandler: students }, connectProfileController)
  app.post('/stories', { preHandler: students }, createStoryController)
  app.get('/stories', { preHandler: students }, listStoriesController)
  app.get('/stories/:id/engagement', { preHandler: students }, readStoryEngagementController)
  app.post('/stories/:id/reactions', { preHandler: students }, reactToStoryController)
  app.post('/stories/:id/comments', { preHandler: students }, commentOnStoryController)
  app.post('/stories/comments/:id/reactions', { preHandler: students }, reactToStoryCommentController)
  app.post('/posts', { preHandler: students }, createPostController)
  app.get('/event-organizers', { preHandler: authenticatedUsers }, searchEventOrganizersController)
  app.patch('/posts/:id', { preHandler: students }, updateOwnedPostController)
  app.post('/posts/:id/reactions', { preHandler: students }, reactToPostController)
  app.post('/posts/:id/comments', { preHandler: students }, commentOnPostController)
  app.post('/posts/:id/report', { preHandler: students }, reportPostController)
  app.get('/announcements/targets', { preHandler: students }, readAnnouncementTargetsController)
  app.post('/posts/:id/announcement-submissions', { preHandler: students }, submitPostForAnnouncementController)
  app.get('/admin/announcement-submissions', { preHandler: announcementAdmins }, listAnnouncementRequestsController)
  app.patch('/admin/announcement-submissions/:id', { preHandler: announcementAdmins }, decideAnnouncementRequestController)
  app.get('/tags/:type/:id/context', { preHandler: students }, readTagContextController)
  app.post('/groups', { preHandler: students }, createGroupController)
  app.get('/groups', { preHandler: students }, listGroupsController)
  app.post('/groups/:id/join', { preHandler: students }, joinGroupController)
  app.post('/groups/:id/chama-contributions', { preHandler: students }, contributeToChamaController)
}

export {
  registerConnectRoutes
}
