import { Navigate } from "react-router-dom";
import { ACCESS_KEYS } from "../auth/roleConfig";
import {
  AuthPage,
  BusinessApplicantsBrowsePage,
  BusinessCreateMarketingCampaignPage,
  BusinessCreateOpportunityPage,
  BusinessCompanyProfilePage,
  BusinessKycPage,
  BusinessMarketingCampaignPage,
  BusinessMarketingPage,
  BusinessOnboardingPage,
  BusinessOpportunitiesPage,
  BusinessPage,
  BusinessProjectsPage,
  BusinessServicesBrowsePage,
  BusinessSettingsPage,
  BusinessWorkspacePage,
  CampusCartOrderPlacedPage,
  CampusCartPage,
  CampusCartPaymentPage,
  CampusCartReviewPage,
  CallRoomPage,
  CampusPage,
  CampusProfilePage,
  ExploreCampusPage,
  HelpPage,
  HomePage,
  KnowledgeSpacePage,
  LearnPage,
  LearnAssessmentPage,
  LearnPracticePage,
  MessagesPage,
  MarketplaceListingStudioPage,
  ManagedProfilePage,
  OpportunityPlaceBidPage,
  OpportunitiesBuySellPage,
  OpportunitiesBuySellProductPage,
  OpportunitiesPage,
  ProjectWorkspacePage,
  StudentMarketingCampaignPage,
  StudentInterviewPage,
  SuperAdminPage,
} from "./routePages";

export const APP_ROUTES = [
  { path: "/", element: <HomePage /> },
  { path: "/campus", access: ACCESS_KEYS.campus.home, element: <CampusPage /> },
  {
    path: "/campus/cart",
    access: ACCESS_KEYS.cart.view,
    element: <CampusCartPage />,
  },
  {
    path: "/campus/cart/payment",
    access: ACCESS_KEYS.cart.checkout,
    element: <CampusCartPaymentPage />,
  },
  {
    path: "/campus/cart/review",
    access: ACCESS_KEYS.cart.checkout,
    element: <CampusCartReviewPage />,
  },
  {
    path: "/campus/cart/order-placed",
    access: ACCESS_KEYS.cart.checkout,
    element: <CampusCartOrderPlacedPage />,
  },
  {
    path: "/campus/profile",
    access: ACCESS_KEYS.profile.viewOwn,
    element: <CampusProfilePage />,
  },
  {
    path: "/campus/profiles/:studentId",
    access: ACCESS_KEYS.profile.viewOwn,
    element: <CampusProfilePage />,
  },
  {
    path: "/campus/organizations/:profileSlug",
    access: ACCESS_KEYS.campus.explore,
    element: <ManagedProfilePage />,
  },
  {
    path: "/campus/explore",
    access: ACCESS_KEYS.campus.explore,
    element: <ExploreCampusPage />,
  },
  {
    path: "/campus/community",
    element: <Navigate to="/campus/explore" replace />,
  },
  {
    path: "/campus/learn",
    access: ACCESS_KEYS.campus.learn,
    element: <LearnPage />,
  },
  {
    path: "/campus/learn/spaces/:spaceSlug",
    access: ACCESS_KEYS.campus.learn,
    element: <KnowledgeSpacePage />,
  },
  {
    path: "/campus/learn/:enrollmentId/checkpoints/:checkpointId/assessment",
    access: ACCESS_KEYS.campus.learn,
    element: <LearnAssessmentPage />,
  },
  {
    path: "/campus/learn/:enrollmentId/checkpoints/:checkpointId/practice/:resourceId",
    access: ACCESS_KEYS.campus.learn,
    element: <LearnPracticePage />,
  },
  {
    path: "/campus/opportunities",
    access: ACCESS_KEYS.campus.opportunities,
    element: <OpportunitiesPage />,
  },
  {
    path: "/campus/opportunities/buy-sell",
    access: ACCESS_KEYS.marketplace.view,
    element: <OpportunitiesBuySellPage />,
  },
  {
    path: "/campus/services",
    access: ACCESS_KEYS.marketplace.view,
    element: <Navigate to="/campus/opportunities/buy-sell?mode=services" replace />,
  },
  {
    path: "/campus/marketplace/listings/new",
    access: ACCESS_KEYS.marketplace.sell,
    element: <MarketplaceListingStudioPage />,
  },
  {
    path: "/campus/marketplace/listings/:listingId/edit",
    access: ACCESS_KEYS.marketplace.sell,
    element: <MarketplaceListingStudioPage />,
  },
  {
    path: "/campus/opportunities/buy-sell/:itemId",
    access: ACCESS_KEYS.marketplace.view,
    element: <OpportunitiesBuySellProductPage />,
  },
  {
    path: "/campus/opportunities/:opportunityId/place-bid",
    access: ACCESS_KEYS.opportunities.apply,
    element: <OpportunityPlaceBidPage />,
  },
  {
    path: "/campus/opportunities/marketing/:campaignId",
    access: ACCESS_KEYS.opportunities.apply,
    element: <StudentMarketingCampaignPage />,
  },
  {
    path: "/campus/opportunities/jobs-gigs",
    element: <Navigate to="/campus/opportunities" replace />,
  },
  {
    path: "/campus/interviews/:interviewId",
    access: ACCESS_KEYS.opportunities.apply,
    element: <StudentInterviewPage />,
  },
  {
    path: "/campus/projects/:projectId",
    access: ACCESS_KEYS.projects.view,
    element: <ProjectWorkspacePage />,
  },
  {
    path: "/business/projects/:projectId",
    access: ACCESS_KEYS.projects.view,
    element: <ProjectWorkspacePage />,
  },
  {
    path: "/business/projects",
    access: ACCESS_KEYS.projects.view,
    element: <BusinessProjectsPage />,
  },
  { path: "/business", element: <BusinessPage /> },
  { path: "/calls/:callId", element: <CallRoomPage /> },
  {
    path: "/business/onboarding",
    access: ACCESS_KEYS.business.dashboard,
    element: <BusinessOnboardingPage />,
  },
  {
    path: "/business/workspace",
    access: ACCESS_KEYS.business.dashboard,
    element: <BusinessWorkspacePage />,
  },
  {
    path: "/business/kyc",
    access: ACCESS_KEYS.business.dashboard,
    element: <BusinessKycPage />,
  },
  {
    path: "/business/marketing",
    access: ACCESS_KEYS.business.marketing,
    element: <BusinessMarketingPage />,
  },
  {
    path: "/business/marketing/create",
    access: ACCESS_KEYS.business.marketingCreate,
    element: <BusinessCreateMarketingCampaignPage />,
  },
  {
    path: "/business/marketing/:campaignId/edit",
    access: ACCESS_KEYS.business.marketingCreate,
    element: <BusinessCreateMarketingCampaignPage />,
  },
  {
    path: "/business/marketing/:campaignId",
    access: ACCESS_KEYS.business.marketing,
    element: <BusinessMarketingCampaignPage />,
  },
  {
    path: "/business/opportunities",
    access: ACCESS_KEYS.business.postOpportunities,
    element: <BusinessOpportunitiesPage />,
  },
  {
    path: "/business/opportunities/create",
    access: ACCESS_KEYS.business.postOpportunities,
    element: <BusinessCreateOpportunityPage />,
  },
  {
    path: "/business/applicants",
    access: [
      ACCESS_KEYS.business.applicantProfiles,
      ACCESS_KEYS.business.applicantProfilesLimited,
    ],
    element: <BusinessApplicantsBrowsePage />,
  },
  {
    path: "/business/services",
    access: [
      ACCESS_KEYS.business.applicantProfiles,
      ACCESS_KEYS.business.applicantProfilesLimited,
    ],
    element: <BusinessServicesBrowsePage />,
  },
  {
    path: "/business/applicant-profile",
    access: [
      ACCESS_KEYS.business.applicantProfiles,
      ACCESS_KEYS.business.applicantProfilesLimited,
    ],
    element: <CampusProfilePage viewContext="business" />,
  },
  {
    path: "/business/company-profile",
    access: ACCESS_KEYS.business.companyProfile,
    element: <BusinessCompanyProfilePage />,
  },
  {
    path: "/business/settings",
    access: ACCESS_KEYS.business.settings,
    element: <BusinessSettingsPage />,
  },
  { path: "/help", element: <HelpPage /> },
  {
    path: "/messages",
    access: [ACCESS_KEYS.campus.messages, ACCESS_KEYS.business.messages],
    element: <MessagesPage />,
  },
  {
    path: "/admin/super-admin",
    access: ACCESS_KEYS.platform.all,
    element: <SuperAdminPage />,
  },
  { path: "/login", element: <AuthPage defaultMode="login" /> },
  { path: "/register", element: <AuthPage defaultMode="register" /> },
  { path: "/web/login", element: <Navigate to="/login" replace /> },
  { path: "/web/login.html", element: <Navigate to="/login" replace /> },
  { path: "/web/signup", element: <Navigate to="/register" replace /> },
  { path: "/web/signup.html", element: <Navigate to="/register" replace /> },
  { path: "/trial.html", element: <Navigate to="/register" replace /> },
  { path: "*", element: <Navigate to="/" replace /> },
];
