import { lazy } from 'react'

export const AuthPage = lazy(() => import('../../pages/AuthPage'))
export const BusinessApplicantProfilePage = lazy(() => import('../../pages/BusinessApplicantProfilePage'))
export const BusinessCreateMarketingCampaignPage = lazy(() => import('../../pages/BusinessCreateMarketingCampaignPage'))
export const BusinessCreateOpportunityPage = lazy(() => import('../../pages/BusinessCreateOpportunityPage'))
export const BusinessMarketingCampaignPage = lazy(() => import('../../pages/BusinessMarketingCampaignPage'))
export const BusinessMarketingPage = lazy(() => import('../../pages/BusinessMarketingPage'))
export const BusinessOpportunitiesPage = lazy(() => import('../../pages/BusinessOpportunitiesPage'))
export const BusinessPage = lazy(() => import('../../pages/BusinessPage'))
export const BusinessWorkspacePage = lazy(() => import('../../pages/BusinessWorkspacePage'))
export const CampusCartOrderPlacedPage = lazy(() => import('../../pages/CampusCartOrderPlacedPage'))
export const CampusCartPage = lazy(() => import('../../pages/CampusCartPage'))
export const CampusCartPaymentPage = lazy(() => import('../../pages/CampusCartPaymentPage'))
export const CampusCartReviewPage = lazy(() => import('../../pages/CampusCartReviewPage'))
export const CampusPage = lazy(() => import('../../pages/CampusPage'))
export const CampusProfilePage = lazy(() => import('../../pages/CampusProfilePage'))
export const ExploreCampusPage = lazy(() => import('../../pages/ExploreCampusPage'))
export const HelpPage = lazy(() => import('../../pages/HelpPage'))
export const HomePage = lazy(() => import('../../pages/HomePage'))
export const LearnPage = lazy(() => import('../../pages/LearnPage'))
export const OpportunityPlaceBidPage = lazy(() => import('../../pages/OpportunityPlaceBidPage'))
export const OpportunitiesBuySellPage = lazy(() => import('../../pages/OpportunitiesBuySellPage'))
export const OpportunitiesBuySellProductPage = lazy(() => import('../../pages/OpportunitiesBuySellProductPage'))
export const OpportunitiesPage = lazy(() => import('../../pages/OpportunitiesPage'))
export const ProjectWorkspacePage = lazy(() => import('../../pages/ProjectWorkspacePage'))
export const StudentMarketingCampaignPage = lazy(() => import('../../pages/StudentMarketingCampaignPage'))
