import { Navigate } from "react-router-dom";
import { ACCESS_KEYS } from "../auth/roleConfig";
import CampusLandingRedirect from "./components/CampusLandingRedirect";
import {
  AuthPage,
  BusinessApplicantsBrowsePage,
  BusinessCreateMarketingCampaignPage,
  BusinessCreateOpportunityPage,
  BusinessCompanyProfilePage,
  BusinessKycPage,
  BusinessMarketingCampaignPage,
  BusinessMarketingPage,
  BusinessOnboardingPage,
  BusinessOpportunitiesPage,
  BusinessPage,
  BusinessProjectsPage,
  BusinessServicesBrowsePage,
  BusinessSettingsPage,
  BusinessWorkspacePage,
  CampusCartOrderPlacedPage,
  CampusCartPage,
  CampusCartPaymentPage,
  CampusCartReviewPage,
  CallRoomPage,
  CampusPage,
  CampusProfilePage,
  CampusVendorProfilePage,
  CampusVendorWorkspacePage,
  ExploreCampusPage,
  HelpPage,
  HomePage,
  KnowledgeSpacePage,
  LearnPage,
  LearnAssessmentPage,
  LearnPracticePage,
  MessagesPage,
  MarketplaceListingStudioPage,
  ManagedProfilePage,
  OpportunityPlaceBidPage,
  OpportunitiesBuySellPage,
  OpportunitiesBuySellProductPage,
  OpportunitiesPage,
  ProjectWorkspacePage,
  StudentMarketingCampaignPage,
  StudentInterviewPage,
  SuperAdminPage,
  SupportCirclePage,
  WellbeingPage,
  EvergreenWorkspacePage,
} from "./routePages";

export const APP_ROUTES = [
  { path: "/", element: <HomePage /> },
  { path: "/campus/landing", access: ACCESS_KEYS.campus.home, element: <CampusLandingRedirect /> },
  { path: "/campus", access: ACCESS_KEYS.campus.home, element: <ExploreCampusPage /> },
  {
    path: "/campus/workspace",
    access: ACCESS_KEYS.campus.home,
    element: <CampusPage />,
  },
  {
    path: "/campus/cart",
    access: ACCESS_KEYS.cart.view,
    element: <CampusCartPage />,
  },
  {
    path: "/campus/cart/payment",
    access: ACCESS_KEYS.cart.checkout,
    element: <CampusCartPaymentPage />,
  },
  {
    path: "/campus/cart/review",
    access: ACCESS_KEYS.cart.checkout,
    element: <CampusCartReviewPage />,
  },
  {
    path: "/campus/cart/order-placed",
    access: ACCESS_KEYS.cart.checkout,
    element: <CampusCartOrderPlacedPage />,
  },
  {
    path: "/campus/profile",
    access: ACCESS_KEYS.profile.viewOwn,
    element: <CampusProfilePage />,
  },
  {
    path: "/campus/profiles/:studentId",
    access: ACCESS_KEYS.profile.viewOwn,
    element: <CampusProfilePage />,
  },
  {
    path: "/campus/organizations/:profileSlug",
    access: ACCESS_KEYS.campus.explore,
    element: <ManagedProfilePage />,
  },
  {
    path: "/campus/explore",
    access: ACCESS_KEYS.campus.explore,
    element: <ExploreCampusPage />,
  },
  {
    path: "/campus/wellbeing",
    access: ACCESS_KEYS.campus.wellness,
    element: <WellbeingPage />,
  },
  {
    path: "/campus/wellbeing/circles/:groupId",
    access: ACCESS_KEYS.campus.wellness,
    element: <SupportCirclePage />,
  },
  { path: "/campus/community", element: <Navigate to="/campus/wellbeing" replace /> },
  { path: "/campus/community/wellbeing", element: <Navigate to="/campus/wellbeing" replace /> },
  {
    path: "/campus/learn",
    access: ACCESS_KEYS.campus.learn,
    element: <LearnPage />,
  },
  {
    path: "/campus/career/evergreen",
    access: ACCESS_KEYS.campus.learn,
    element: <EvergreenWorkspacePage surface="student" view="readiness" />,
  },
  {
    path: "/campus/career/evergreen/readiness",
    access: ACCESS_KEYS.campus.learn,
    element: <EvergreenWorkspacePage surface="student" view="readiness" />,
  },
  {
    path: "/campus/career/evergreen/matches",
    access: ACCESS_KEYS.opportunities.placementAvailability,
    element: <EvergreenWorkspacePage surface="student" view="matches" />,
  },
  {
    path: "/campus/career/evergreen/offers",
    access: ACCESS_KEYS.opportunities.formalOffers,
    element: <EvergreenWorkspacePage surface="student" view="offers" />,
  },
  {
    path: "/campus/career/evergreen/offers/:offerId",
    access: ACCESS_KEYS.opportunities.formalOffers,
    element: <EvergreenWorkspacePage surface="student" view="offers" />,
  },
  {
    path: "/campus/career/evergreen/placements",
    access: ACCESS_KEYS.opportunities.ownPipeline,
    element: <EvergreenWorkspacePage surface="student" view="placements" />,
  },
  {
    path: "/campus/career/evergreen/placements/:placementId",
    access: ACCESS_KEYS.opportunities.ownPipeline,
    element: <EvergreenWorkspacePage surface="student" view="placement" />,
  },
  {
    path: "/campus/learn/spaces/:spaceSlug",
    access: ACCESS_KEYS.campus.learn,
    element: <KnowledgeSpacePage />,
  },
  {
    path: "/campus/learn/:enrollmentId/checkpoints/:checkpointId/assessment",
    access: ACCESS_KEYS.campus.learn,
    element: <LearnAssessmentPage />,
  },
  {
    path: "/campus/learn/:enrollmentId/checkpoints/:checkpointId/practice/:resourceId",
    access: ACCESS_KEYS.campus.learn,
    element: <LearnPracticePage />,
  },
  {
    path: "/campus/opportunities",
    access: ACCESS_KEYS.campus.opportunities,
    element: <OpportunitiesPage />,
  },
  {
    path: "/campus/opportunities/buy-sell",
    access: ACCESS_KEYS.marketplace.view,
    element: <OpportunitiesBuySellPage />,
  },
  {
    path: "/campus/services",
    access: ACCESS_KEYS.marketplace.view,
    element: <Navigate to="/campus/opportunities/buy-sell?mode=services" replace />,
  },
  {
    path: "/campus/marketplace/listings/new",
    access: ACCESS_KEYS.marketplace.sell,
    element: <MarketplaceListingStudioPage />,
  },
  {
    path: "/campus/vendors/:vendorSlug",
    access: ACCESS_KEYS.marketplace.view,
    element: <CampusVendorProfilePage />,
  },
  {
    path: "/campus/vendors/:vendorSlug/manage",
    access: ACCESS_KEYS.marketplace.sell,
    element: <CampusVendorWorkspacePage />,
  },
  {
    path: "/campus/marketplace/listings/:listingId/edit",
    access: ACCESS_KEYS.marketplace.sell,
    element: <MarketplaceListingStudioPage />,
  },
  {
    path: "/campus/opportunities/buy-sell/:itemId",
    access: ACCESS_KEYS.marketplace.view,
    element: <OpportunitiesBuySellProductPage />,
  },
  {
    path: "/campus/opportunities/:opportunityId/place-bid",
    access: ACCESS_KEYS.opportunities.apply,
    element: <OpportunityPlaceBidPage />,
  },
  {
    path: "/campus/opportunities/marketing/:campaignId",
    access: ACCESS_KEYS.opportunities.apply,
    element: <StudentMarketingCampaignPage />,
  },
  {
    path: "/campus/opportunities/jobs-gigs",
    element: <Navigate to="/campus/opportunities" replace />,
  },
  {
    path: "/campus/interviews/:interviewId",
    access: ACCESS_KEYS.opportunities.apply,
    element: <StudentInterviewPage />,
  },
  {
    path: "/campus/projects/:projectId",
    access: ACCESS_KEYS.projects.view,
    element: <ProjectWorkspacePage />,
  },
  {
    path: "/business/projects/:projectId",
    access: ACCESS_KEYS.projects.view,
    element: <ProjectWorkspacePage />,
  },
  {
    path: "/business/projects",
    access: ACCESS_KEYS.projects.view,
    element: <BusinessProjectsPage />,
  },
  {
    path: "/business/evergreen",
    access: [ACCESS_KEYS.business.pipelineBasic, ACCESS_KEYS.business.pipelineFull, ACCESS_KEYS.business.pipelineRead],
    element: <EvergreenWorkspacePage surface="company" view="overview" />,
  },
  {
    path: "/business/evergreen/programs/new",
    access: ACCESS_KEYS.business.pipelineFull,
    element: <EvergreenWorkspacePage surface="company" view="new-program" />,
  },
  {
    path: "/business/evergreen/programs/:programId",
    access: [ACCESS_KEYS.business.pipelineBasic, ACCESS_KEYS.business.pipelineFull, ACCESS_KEYS.business.pipelineRead],
    element: <EvergreenWorkspacePage surface="company" view="program" />,
  },
  {
    path: "/business/evergreen/cohorts/:cohortId",
    access: [ACCESS_KEYS.business.pipelineFull, ACCESS_KEYS.business.pipelineRead],
    element: <EvergreenWorkspacePage surface="company" view="cohort" />,
  },
  {
    path: "/business/evergreen/placements/:placementId",
    access: [ACCESS_KEYS.business.pipelineFull, ACCESS_KEYS.business.pipelineRead],
    element: <EvergreenWorkspacePage surface="company" view="placement" />,
  },
  { path: "/business", element: <BusinessPage /> },
  { path: "/calls/:callId", element: <CallRoomPage /> },
  {
    path: "/business/onboarding",
    access: ACCESS_KEYS.business.dashboard,
    element: <BusinessOnboardingPage />,
  },
  {
    path: "/business/workspace",
    access: ACCESS_KEYS.business.dashboard,
    element: <BusinessWorkspacePage />,
  },
  {
    path: "/business/kyc",
    access: ACCESS_KEYS.business.dashboard,
    element: <BusinessKycPage />,
  },
  {
    path: "/business/marketing",
    access: ACCESS_KEYS.business.marketing,
    element: <BusinessMarketingPage />,
  },
  {
    path: "/business/marketing/create",
    access: ACCESS_KEYS.business.marketingCreate,
    element: <BusinessCreateMarketingCampaignPage />,
  },
  {
    path: "/business/marketing/:campaignId/edit",
    access: ACCESS_KEYS.business.marketingCreate,
    element: <BusinessCreateMarketingCampaignPage />,
  },
  {
    path: "/business/marketing/:campaignId",
    access: ACCESS_KEYS.business.marketing,
    element: <BusinessMarketingCampaignPage />,
  },
  {
    path: "/business/opportunities",
    access: ACCESS_KEYS.business.postOpportunities,
    element: <BusinessOpportunitiesPage />,
  },
  {
    path: "/business/opportunities/create",
    access: ACCESS_KEYS.business.postOpportunities,
    element: <BusinessCreateOpportunityPage />,
  },
  {
    path: "/business/applicants",
    access: [
      ACCESS_KEYS.business.applicantProfiles,
      ACCESS_KEYS.business.applicantProfilesLimited,
    ],
    element: <BusinessApplicantsBrowsePage />,
  },
  {
    path: "/business/services",
    access: [
      ACCESS_KEYS.business.applicantProfiles,
      ACCESS_KEYS.business.applicantProfilesLimited,
    ],
    element: <BusinessServicesBrowsePage />,
  },
  {
    path: "/business/applicant-profile",
    access: [
      ACCESS_KEYS.business.applicantProfiles,
      ACCESS_KEYS.business.applicantProfilesLimited,
    ],
    element: <CampusProfilePage viewContext="business" />,
  },
  {
    path: "/business/company-profile",
    access: ACCESS_KEYS.business.companyProfile,
    element: <BusinessCompanyProfilePage />,
  },
  {
    path: "/business/settings",
    access: ACCESS_KEYS.business.settings,
    element: <BusinessSettingsPage />,
  },
  { path: "/help", element: <HelpPage /> },
  {
    path: "/messages",
    access: [ACCESS_KEYS.campus.messages, ACCESS_KEYS.business.messages],
    element: <MessagesPage />,
  },
  {
    path: "/admin/super-admin",
    access: ACCESS_KEYS.platform.all,
    element: <SuperAdminPage />,
  },
  {
    path: "/admin/evergreen/reviews",
    access: ACCESS_KEYS.platform.gigOversight,
    element: <EvergreenWorkspacePage surface="operations" view="reviews" />,
  },
  {
    path: "/admin/evergreen/cohorts",
    access: ACCESS_KEYS.platform.gigOversight,
    element: <EvergreenWorkspacePage surface="operations" view="reviews" />,
  },
  {
    path: "/admin/evergreen/placements",
    access: ACCESS_KEYS.platform.gigOversight,
    element: <EvergreenWorkspacePage surface="operations" view="placements" />,
  },
  {
    path: "/admin/evergreen/exceptions",
    access: ACCESS_KEYS.platform.gigOversight,
    element: <EvergreenWorkspacePage surface="operations" view="exceptions" />,
  },
  {
    path: "/admin/evergreen/billing",
    access: ACCESS_KEYS.finance.billing,
    element: <EvergreenWorkspacePage surface="operations" view="billing" />,
  },
  { path: "/login", element: <AuthPage defaultMode="login" /> },
  { path: "/register", element: <AuthPage defaultMode="register" /> },
  { path: "/web/login", element: <Navigate to="/login" replace /> },
  { path: "/web/login.html", element: <Navigate to="/login" replace /> },
  { path: "/web/signup", element: <Navigate to="/register" replace /> },
  { path: "/web/signup.html", element: <Navigate to="/register" replace /> },
  { path: "/trial.html", element: <Navigate to="/register" replace /> },
  { path: "*", element: <Navigate to="/" replace /> },
];
