import { Navigate } from 'react-router-dom'
import { ACCESS_KEYS } from '../auth/roleConfig'
import {
  AuthPage,
  BusinessApplicantProfilePage,
  BusinessCreateMarketingCampaignPage,
  BusinessCreateOpportunityPage,
  BusinessMarketingCampaignPage,
  BusinessMarketingPage,
  BusinessOpportunitiesPage,
  BusinessPage,
  BusinessWorkspacePage,
  CampusCartOrderPlacedPage,
  CampusCartPage,
  CampusCartPaymentPage,
  CampusCartReviewPage,
  CampusPage,
  CampusProfilePage,
  ExploreCampusPage,
  HelpPage,
  HomePage,
  LearnPage,
  OpportunityPlaceBidPage,
  OpportunitiesBuySellPage,
  OpportunitiesBuySellProductPage,
  OpportunitiesPage,
  ProjectWorkspacePage,
  StudentMarketingCampaignPage,
} from './routePages'

export const APP_ROUTES = [
  { path: '/', element: <HomePage /> },
  { path: '/campus', access: ACCESS_KEYS.campus.home, element: <CampusPage /> },
  { path: '/campus/cart', access: ACCESS_KEYS.cart.view, element: <CampusCartPage /> },
  { path: '/campus/cart/payment', access: ACCESS_KEYS.cart.checkout, element: <CampusCartPaymentPage /> },
  { path: '/campus/cart/review', access: ACCESS_KEYS.cart.checkout, element: <CampusCartReviewPage /> },
  {
    path: '/campus/cart/order-placed',
    access: ACCESS_KEYS.cart.checkout,
    element: <CampusCartOrderPlacedPage />,
  },
  { path: '/campus/profile', access: ACCESS_KEYS.profile.viewOwn, element: <CampusProfilePage /> },
  { path: '/campus/explore', access: ACCESS_KEYS.campus.explore, element: <ExploreCampusPage /> },
  { path: '/campus/community', element: <Navigate to="/campus/explore" replace /> },
  { path: '/campus/learn', access: ACCESS_KEYS.campus.learn, element: <LearnPage /> },
  { path: '/campus/opportunities', access: ACCESS_KEYS.campus.opportunities, element: <OpportunitiesPage /> },
  {
    path: '/campus/opportunities/buy-sell',
    access: ACCESS_KEYS.marketplace.view,
    element: <OpportunitiesBuySellPage />,
  },
  {
    path: '/campus/opportunities/buy-sell/:itemId',
    access: ACCESS_KEYS.marketplace.view,
    element: <OpportunitiesBuySellProductPage />,
  },
  {
    path: '/campus/opportunities/:opportunityId/place-bid',
    access: ACCESS_KEYS.opportunities.apply,
    element: <OpportunityPlaceBidPage />,
  },
  {
    path: '/campus/opportunities/marketing/:campaignId',
    access: ACCESS_KEYS.opportunities.apply,
    element: <StudentMarketingCampaignPage />,
  },
  { path: '/campus/opportunities/jobs-gigs', element: <Navigate to="/campus/opportunities" replace /> },
  { path: '/campus/projects/:projectId', access: ACCESS_KEYS.projects.view, element: <ProjectWorkspacePage /> },
  { path: '/business', element: <BusinessPage /> },
  { path: '/business/workspace', access: ACCESS_KEYS.business.dashboard, element: <BusinessWorkspacePage /> },
  { path: '/business/marketing', access: ACCESS_KEYS.business.marketing, element: <BusinessMarketingPage /> },
  {
    path: '/business/marketing/create',
    access: ACCESS_KEYS.business.marketingCreate,
    element: <BusinessCreateMarketingCampaignPage />,
  },
  {
    path: '/business/marketing/:campaignId',
    access: ACCESS_KEYS.business.marketing,
    element: <BusinessMarketingCampaignPage />,
  },
  {
    path: '/business/opportunities',
    access: ACCESS_KEYS.business.postOpportunities,
    element: <BusinessOpportunitiesPage />,
  },
  {
    path: '/business/opportunities/create',
    access: ACCESS_KEYS.business.postOpportunities,
    element: <BusinessCreateOpportunityPage />,
  },
  {
    path: '/business/applicant-profile',
    access: [ACCESS_KEYS.business.applicantProfiles, ACCESS_KEYS.business.applicantProfilesLimited],
    element: <BusinessApplicantProfilePage />,
  },
  { path: '/help', element: <HelpPage /> },
  { path: '/login', element: <AuthPage defaultMode="login" /> },
  { path: '/register', element: <AuthPage defaultMode="register" /> },
  { path: '/web/login', element: <Navigate to="/login" replace /> },
  { path: '/web/login.html', element: <Navigate to="/login" replace /> },
  { path: '/web/signup', element: <Navigate to="/register" replace /> },
  { path: '/web/signup.html', element: <Navigate to="/register" replace /> },
  { path: '/trial.html', element: <Navigate to="/register" replace /> },
  { path: '*', element: <Navigate to="/" replace /> },
]
