import { sendZumbarlApiRequest } from '../../../lib/sendZumbarlApiRequest'

function request(path, method = 'GET', body, idempotencyKey) {
  return sendZumbarlApiRequest(`/evergreen${path}`, {
    method,
    ...(body === undefined ? {} : { body: JSON.stringify(body) }),
    ...(idempotencyKey ? { headers: { 'Idempotency-Key': idempotencyKey } } : {}),
  })
}

const evergreenService = {
  eligibility: () => request('/eligibility'),
  programs: () => request('/programs'),
  program: (id) => request(`/programs/${id}`),
  createProgram: (body) => request('/programs', 'POST', body),
  updateProgram: (id, body) => request(`/programs/${id}`, 'PATCH', body),
  submitProgram: (id) => request(`/programs/${id}/submit`, 'POST'),
  pauseProgram: (id) => request(`/programs/${id}/pause`, 'POST'),
  createCohort: (programId, body) => request(`/programs/${programId}/cohorts`, 'POST', body, crypto.randomUUID()),
  cohort: (id) => request(`/cohorts/${id}`),
  candidates: (id) => request(`/cohorts/${id}/candidates`),
  candidateAction: (id, action, body) => request(`/candidates/${id}/${action}`, 'POST', body),
  createOffer: (candidateId, body) => request(`/candidates/${candidateId}/offers`, 'POST', body),
  sendOffer: (id) => request(`/offers/${id}/send`, 'POST'),
  readiness: () => request('/student/readiness'),
  setAvailability: (body) => request('/student/availability', 'PUT', body),
  pauseAvailability: () => request('/student/availability/pause', 'POST'),
  matches: () => request('/student/matches'),
  apply: (cohortId) => request(`/cohorts/${cohortId}/applications`, 'POST'),
  offers: () => request('/student/offers'),
  acceptOffer: (id) => request(`/offers/${id}/accept`, 'POST', undefined, crypto.randomUUID()),
  declineOffer: (id, reason) => request(`/offers/${id}/decline`, 'POST', { reason }),
  placements: () => request('/student/placements'),
  placement: (id) => request(`/placements/${id}`),
  completeOnboarding: (id, itemId) => request(`/placements/${id}/onboarding`, 'POST', { itemId }),
  submitCheckIn: (id, body) => request(`/placements/${id}/check-ins`, 'POST', body),
  submitEvidence: (id, body) => request(`/placements/${id}/evidence`, 'POST', body),
  verifyEvidence: (id, evidenceId) => request(`/placements/${id}/evidence/${evidenceId}/verify`, 'POST'),
  createGoal: (id, body) => request(`/placements/${id}/goals`, 'POST', body),
  createEvaluation: (id, body) => request(`/placements/${id}/evaluations`, 'POST', body),
  createAmendment: (id, body) => request(`/placements/${id}/amendments`, 'POST', body),
  decideAmendment: (id, amendmentId, body) => request(`/placements/${id}/amendments/${amendmentId}/decision`, 'POST', body),
  requestSupport: (id, body) => request(`/placements/${id}/support-requests`, 'POST', body),
  startPlacement: (id) => request(`/placements/${id}/start`, 'POST'),
  completePlacement: (id, reason) => request(`/placements/${id}/complete`, 'POST', { reason }),
  cancelPlacement: (id, reason) => request(`/placements/${id}/cancel`, 'POST', { reason }),
  terminatePlacement: (id, reason) => request(`/placements/${id}/terminate`, 'POST', { reason }),
  submitCompletion: (id, reason) => request(`/placements/${id}/completion`, 'POST', { reason }),
  programReviews: () => request('/admin/program-reviews'),
  approveProgram: (id) => request(`/admin/programs/${id}/approve`, 'POST'),
  requestChanges: (id, reason) => request(`/admin/programs/${id}/request-changes`, 'POST', { reason }),
  placementAlerts: () => request('/admin/placement-alerts'),
  supportRequests: () => request('/admin/support-requests'),
  resolveSupportRequest: (id, resolution) => request(`/admin/support-requests/${id}/resolve`, 'POST', { resolution }),
  resolvePlacement: (id, body) => request(`/admin/placements/${id}/resolve`, 'POST', body),
  createOverride: (body) => request('/admin/overrides', 'POST', body),
  createMentorshipAlternative: (body) => request('/admin/mentorship-alternatives', 'POST', body),
  replayJob: (name) => request(`/admin/jobs/${name}/replay`, 'POST'),
  failures: () => request('/admin/failures'),
  replayEvent: (id) => request(`/admin/events/${id}/replay`, 'POST'),
  createInvoice: (body) => request('/finance/invoices', 'POST', body),
  confirmInvoice: (id, body) => request(`/finance/invoices/${id}/confirm`, 'POST', body),
  refundInvoice: (id, reason) => request(`/finance/invoices/${id}/refund`, 'POST', { reason }),
  changeEntitlementStatus: (id, body) => request(`/finance/entitlements/${id}/status`, 'POST', body),
}

export default evergreenService
